[tool.poetry]
name = "globe40"
version = "0.1.0"
description = ""
authors = ["Kass Schmitt <kass.schmitt@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
geojson = "^3.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
